#!/bin/bash

echo "🔍 LiveKit Server Status Check"
echo "==============================="
echo ""
echo "Please run these commands on your server:"
echo ""
echo "1️⃣ Check if LiveKit container is running:"
echo "   docker-compose ps"
echo ""
echo "2️⃣ Check ALL recent LiveKit logs (not just arena):"
echo "   docker-compose logs --tail=100"
echo ""
echo "3️⃣ Check if LiveKit is listening on port 7880:"
echo "   netstat -tulpn | grep 7880"
echo ""
echo "4️⃣ Test LiveKit health endpoint:"
echo "   curl http://localhost:7880"
echo ""
echo "5️⃣ Check Docker container status:"
echo "   docker ps -a"
echo ""
echo "6️⃣ Check LiveKit configuration:"
echo "   cat livekit-production.yaml"
echo ""
echo "7️⃣ Restart LiveKit if needed:"
echo "   docker-compose down"
echo "   docker-compose up -d"
echo "   docker-compose logs -f"
echo ""
echo "Look for:"
echo "- Container status (should be 'Up')"
echo "- Any ERROR messages in logs"
echo "- Configuration parsing errors"
echo "- Port binding issues"