#!/bin/bash

echo "🔍 LiveKit Server Diagnostics Script"
echo "====================================="
echo ""
echo "Please SSH into your server and run these commands:"
echo ""
echo "1️⃣ SSH into the server:"
echo "   ssh root@172.236.109.9"
echo ""
echo "2️⃣ Check LiveKit service status:"
echo "   cd /opt/livekit-arena"
echo "   docker-compose ps"
echo ""
echo "3️⃣ Check recent LiveKit logs:"
echo "   docker-compose logs --tail=100 | grep -E 'ERROR|WARN|arena-.*connect|ICE|TURN'"
echo ""
echo "4️⃣ Check if the arena room is being created:"
echo "   docker-compose logs --tail=50 | grep -i 'arena-'"
echo ""
echo "5️⃣ Check TURN server connectivity:"
echo "   docker-compose logs --tail=50 | grep -i 'turn'"
echo ""
echo "6️⃣ Check current active rooms:"
echo "   docker-compose exec livekit livekit-cli list-rooms --url ws://localhost:7880 --api-key LKAPI1234567890 --api-secret 7e9fb42854e466daf92dabbc9b88e98f7811486704338e062d30815a592de45d"
echo ""
echo "7️⃣ Test TURN server connectivity from external:"
echo "   curl -v http://openrelay.metered.ca"
echo ""
echo "📋 Look for:"
echo "   - Room creation logs for 'arena-' prefixed rooms"
echo "   - ICE connection failures"
    - TURN server authentication errors"
echo "   - WebRTC handshake issues"
echo "   - Any ERROR or WARN messages"