#!/bin/bash

echo "🕐 Arena Connection Delay Analysis"
echo "==================================="
echo ""
echo "Please run these commands on your server to see what's causing the delay:"
echo ""
echo "1️⃣ Check recent Arena room connections with timestamps:"
echo "   cd /opt/livekit-arena"
echo "   docker-compose logs --tail=200 | grep -E 'arena|ICE|STUN|TURN|candidate|timeout|connect'"
echo ""
echo "2️⃣ Look for ICE gathering delays:"
echo "   docker-compose logs --tail=100 | grep -i 'gathering'"
echo ""
echo "3️⃣ Check TURN server authentication:"
echo "   docker-compose logs --tail=100 | grep -i 'turn.*auth'"
echo ""
echo "4️⃣ Monitor real-time connection as you join Arena:"
echo "   docker-compose logs -f | grep -E 'arena|participant.*joined|ICE'"
echo ""
echo "Common causes of slow connections:"
echo "- ICE gathering timeout (waiting for all candidates)"
echo "- TURN server authentication delays"
echo "- Multiple STUN server timeouts"
echo "- Firewall/NAT traversal retries"
echo "- Server resource constraints"
echo ""
echo "The fact it eventually connects suggests:"
echo "✅ Configuration is correct"
echo "⚠️ But ICE/TURN negotiation is slow"
echo ""
echo "Potential optimizations:"
echo "- Reduce STUN servers to just one reliable one"
echo "- Ensure TURN credentials are correct"
echo "- Check server CPU/memory usage during connection"