#!/bin/bash

# Manual deployment steps for LiveKit v1.5.2 fix
echo "📋 Manual LiveKit Deployment Instructions"
echo "========================================="
echo ""
echo "1️⃣  First, add your SSH key to the server (enter server password when prompted):"
echo "   ssh-copy-id root@172.236.109.9"
echo ""
echo "2️⃣  Then upload the fixed configuration:"
echo "   scp livekit-production-v152.yaml root@172.236.109.9:/opt/livekit-arena/livekit-production.yaml"
echo ""
echo "3️⃣  SSH into the server:"
echo "   ssh root@172.236.109.9"
echo ""
echo "4️⃣  Restart LiveKit with the fixed configuration:"
echo "   cd /opt/livekit-arena"
echo "   docker-compose down"
echo "   docker-compose up -d"
echo ""
echo "5️⃣  Check the logs to confirm it's working:"
echo "   docker-compose logs --tail=50"
echo ""
echo "✅ The configuration fixes:"
echo "   - API key: LKAPI1234567890 (matching Flutter app)"
echo "   - Removed incompatible v1.5.2 fields"
echo "   - Fixed timeout format (600 seconds instead of '10m')"
echo ""
echo "🔑 Your SSH public key (if needed for manual setup):"
cat ~/.ssh/id_rsa.pub