name: arena
description: "A debate and discussion app with live streaming capabilities using Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  appwrite: ^17.0.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  app_links: ^6.0.0
  agora_rtc_engine: ^6.3.2
  permission_handler: ^12.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  audioplayers: ^6.0.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  lucide_icons: ^0.257.0
  get_it: ^7.6.4
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  logger: ^2.0.2+1
  connectivity_plus: ^5.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  test: ^1.24.9

dependency_overrides:
  flutter_web_auth_2: ^4.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/audio/