name: arena
description: "A debate and discussion app with live streaming capabilities using Flutter."
publish_to: 'none'
version: 1.0.32+32

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  appwrite: ^18.0.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  app_links: ^6.0.0
  permission_handler: ^12.0.1
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.1.5
  web_socket_channel: ^3.0.3
  socket_io_client: ^3.1.2
  image_picker: ^1.0.7
  file_picker: ^10.3.2
  file_selector: ^1.0.3
  cached_network_image: ^3.3.1
  audioplayers: ^6.0.0
  audio_session: ^0.2.2
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_messaging: ^16.0.0
  firebase_database: ^12.0.0
  lucide_icons: ^0.257.0
  get_it: ^8.2.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  logger: ^2.0.2+1
  connectivity_plus: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1
  timeago: ^3.6.1
  intl: ^0.20.0
  just_audio: ^0.10.4
  json_annotation: ^4.9.0
  crypto: ^3.0.6
  mcp_toolkit: ^0.3.0
  liquid_glass_renderer: ^0.1.1-dev.9
  flutter_webrtc: ^1.1.0
  http: ^1.1.0
  in_app_purchase: ^3.2.0
  in_app_purchase_storekit: ^0.4.4
  purchases_flutter: ^9.4.0
  flutter_launcher_icons: ^0.14.4
  livekit_client: ^2.3.1
  workmanager: ^0.9.0+2
  share_plus: ^11.1.0
  pdfx: ^2.6.0
  flutter_markdown: ^0.7.4+3
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  test: ^1.24.9

dependency_overrides:
  flutter_web_auth_2: ^4.1.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/audio/
    - TERMS_OF_SERVICE.md
    - PRIVACY_POLICY.md

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/2logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/images/2logo.png"
  web:
    generate: true
    image_path: "assets/images/2logo.png"
    background_color: "#1a1a2e"
    theme_color: "#8b5cf6"
  windows:
    generate: true
    image_path: "assets/images/2logo.png"
    icon_size: 48