#!/bin/bash

echo "🎥 Setting up LiveKit Egress for Go Live feature..."

# SSH into your Linode server and run these commands
echo "Run these commands on your LiveKit server (172.236.109.9):"
echo ""
echo "1. Update LiveKit config:"
echo "   cd /opt/livekit-arena/"
echo "   nano livekit.yaml"
echo ""
echo "2. Add this to your livekit.yaml:"
echo "   egress:"
echo "     enabled: true"
echo "     cpu_cost:"
echo "       room_composite_cpu_cost: 3.0"
echo "       track_composite_cpu_cost: 2.0"
echo "       track_cpu_cost: 1.0"
echo ""
echo "3. Restart LiveKit:"
echo "   docker-compose down && docker-compose up -d"
echo ""
echo "4. Install Egress binary:"
echo "   wget https://github.com/livekit/egress/releases/latest/download/livekit-egress-linux-amd64.tar.gz"
echo "   tar -xzf livekit-egress-linux-amd64.tar.gz"
echo "   sudo mv livekit-egress /usr/local/bin/"
echo ""
echo "5. Start Egress service:"
echo "   livekit-egress --config-file /opt/livekit-arena/livekit.yaml &"
echo ""
echo "✅ After setup, you can Go Live to Facebook, YouTube, Twitch, etc!"