// Mocks generated by Mockito 5.4.4 from annotations
// in arena/test/services/livekit_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;
import 'dart:collection' as _i4;
import 'dart:ui' as _i21;

import 'package:flutter_webrtc/flutter_webrtc.dart' as _i11;
import 'package:livekit_client/livekit_client.dart' as _i34;
import 'package:livekit_client/src/core/engine.dart' as _i2;
import 'package:livekit_client/src/core/room.dart' as _i6;
import 'package:livekit_client/src/e2ee/options.dart' as _i28;
import 'package:livekit_client/src/events.dart' as _i19;
import 'package:livekit_client/src/managers/event.dart' as _i5;
import 'package:livekit_client/src/options.dart' as _i3;
import 'package:livekit_client/src/participant/local.dart' as _i23;
import 'package:livekit_client/src/participant/participant.dart' as _i14;
import 'package:livekit_client/src/participant/remote.dart' as _i13;
import 'package:livekit_client/src/proto/livekit_models.pb.dart' as _i10;
import 'package:livekit_client/src/proto/livekit_rtc.pb.dart' as _i30;
import 'package:livekit_client/src/publication/local.dart' as _i9;
import 'package:livekit_client/src/publication/remote.dart' as _i31;
import 'package:livekit_client/src/publication/track_publication.dart' as _i15;
import 'package:livekit_client/src/support/disposable.dart' as _i22;
import 'package:livekit_client/src/track/local/audio.dart' as _i25;
import 'package:livekit_client/src/track/local/local.dart' as _i8;
import 'package:livekit_client/src/track/local/video.dart' as _i24;
import 'package:livekit_client/src/track/options.dart' as _i29;
import 'package:livekit_client/src/track/remote/audio.dart' as _i33;
import 'package:livekit_client/src/track/remote/video.dart' as _i32;
import 'package:livekit_client/src/track/track.dart' as _i16;
import 'package:livekit_client/src/types/data_stream.dart' as _i18;
import 'package:livekit_client/src/types/other.dart' as _i12;
import 'package:livekit_client/src/types/participant_permissions.dart' as _i7;
import 'package:livekit_client/src/types/participant_state.dart' as _i27;
import 'package:livekit_client/src/types/rpc.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i26;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEngine_0 extends _i1.SmartFake implements _i2.Engine {
  _FakeEngine_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectOptions_1 extends _i1.SmartFake
    implements _i3.ConnectOptions {
  _FakeConnectOptions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoomOptions_2 extends _i1.SmartFake implements _i3.RoomOptions {
  _FakeRoomOptions_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnmodifiableMapView_3<K, V> extends _i1.SmartFake
    implements _i4.UnmodifiableMapView<K, V> {
  _FakeUnmodifiableMapView_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnmodifiableListView_4<E> extends _i1.SmartFake
    implements _i4.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventsEmitter_5<T> extends _i1.SmartFake
    implements _i5.EventsEmitter<T> {
  _FakeEventsEmitter_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventsListener_6<T> extends _i1.SmartFake
    implements _i5.EventsListener<T> {
  _FakeEventsListener_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoom_7 extends _i1.SmartFake implements _i6.Room {
  _FakeRoom_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeParticipantPermissions_8 extends _i1.SmartFake
    implements _i7.ParticipantPermissions {
  _FakeParticipantPermissions_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_9 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalTrackPublication_10<T extends _i8.LocalTrack>
    extends _i1.SmartFake implements _i9.LocalTrackPublication<T> {
  _FakeLocalTrackPublication_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeParticipantTracks_11 extends _i1.SmartFake
    implements _i10.ParticipantTracks {
  _FakeParticipantTracks_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMediaStream_12 extends _i1.SmartFake implements _i11.MediaStream {
  _FakeMediaStream_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMediaStreamTrack_13 extends _i1.SmartFake
    implements _i11.MediaStreamTrack {
  _FakeMediaStreamTrack_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Room].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoom extends _i1.Mock implements _i6.Room {
  MockRoom() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Engine get engine => (super.noSuchMethod(
        Invocation.getter(#engine),
        returnValue: _FakeEngine_0(
          this,
          Invocation.getter(#engine),
        ),
      ) as _i2.Engine);

  @override
  _i12.ConnectionState get connectionState => (super.noSuchMethod(
        Invocation.getter(#connectionState),
        returnValue: _i12.ConnectionState.disconnected,
      ) as _i12.ConnectionState);

  @override
  _i3.ConnectOptions get connectOptions => (super.noSuchMethod(
        Invocation.getter(#connectOptions),
        returnValue: _FakeConnectOptions_1(
          this,
          Invocation.getter(#connectOptions),
        ),
      ) as _i3.ConnectOptions);

  @override
  _i3.RoomOptions get roomOptions => (super.noSuchMethod(
        Invocation.getter(#roomOptions),
        returnValue: _FakeRoomOptions_2(
          this,
          Invocation.getter(#roomOptions),
        ),
      ) as _i3.RoomOptions);

  @override
  _i4.UnmodifiableMapView<String, _i13.RemoteParticipant>
      get remoteParticipants => (super.noSuchMethod(
            Invocation.getter(#remoteParticipants),
            returnValue:
                _FakeUnmodifiableMapView_3<String, _i13.RemoteParticipant>(
              this,
              Invocation.getter(#remoteParticipants),
            ),
          ) as _i4.UnmodifiableMapView<String, _i13.RemoteParticipant>);

  @override
  bool get isRecording => (super.noSuchMethod(
        Invocation.getter(#isRecording),
        returnValue: false,
      ) as bool);

  @override
  _i4.UnmodifiableListView<_i14.Participant<_i15.TrackPublication<_i16.Track>>>
      get activeSpeakers => (super.noSuchMethod(
            Invocation.getter(#activeSpeakers),
            returnValue: _FakeUnmodifiableListView_4<
                _i14.Participant<_i15.TrackPublication<_i16.Track>>>(
              this,
              Invocation.getter(#activeSpeakers),
            ),
          ) as _i4.UnmodifiableListView<
              _i14.Participant<_i15.TrackPublication<_i16.Track>>>);

  @override
  Map<String, _i17.RpcRequestHandler> get rpcHandlers => (super.noSuchMethod(
        Invocation.getter(#rpcHandlers),
        returnValue: <String, _i17.RpcRequestHandler>{},
      ) as Map<String, _i17.RpcRequestHandler>);

  @override
  Map<String, _i18.TextStreamHandler> get textStreamHandlers =>
      (super.noSuchMethod(
        Invocation.getter(#textStreamHandlers),
        returnValue: <String, _i18.TextStreamHandler>{},
      ) as Map<String, _i18.TextStreamHandler>);

  @override
  Map<String, _i18.ByteStreamHandler> get byteStreamHandlers =>
      (super.noSuchMethod(
        Invocation.getter(#byteStreamHandlers),
        returnValue: <String, _i18.ByteStreamHandler>{},
      ) as Map<String, _i18.ByteStreamHandler>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  int get disposeFuncCount => (super.noSuchMethod(
        Invocation.getter(#disposeFuncCount),
        returnValue: 0,
      ) as int);

  @override
  _i5.EventsEmitter<_i19.RoomEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _FakeEventsEmitter_5<_i19.RoomEvent>(
          this,
          Invocation.getter(#events),
        ),
      ) as _i5.EventsEmitter<_i19.RoomEvent>);

  @override
  _i20.Future<void> prepareConnection(
    String? url,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareConnection,
          [
            url,
            token,
          ],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> connect(
    String? url,
    String? token, {
    _i3.ConnectOptions? connectOptions,
    _i3.RoomOptions? roomOptions,
    _i3.FastConnectOptions? fastConnectOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            url,
            token,
          ],
          {
            #connectOptions: connectOptions,
            #roomOptions: roomOptions,
            #fastConnectOptions: fastConnectOptions,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> setE2EEEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setE2EEEnabled,
          [enabled],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i14.Participant<_i15.TrackPublication<_i16.Track>>? getParticipantByIdentity(
          String? identity) =>
      (super.noSuchMethod(Invocation.method(
        #getParticipantByIdentity,
        [identity],
      )) as _i14.Participant<_i15.TrackPublication<_i16.Track>>?);

  @override
  _i20.Future<bool> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  void addListener(_i21.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i21.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose(_i22.OnDisposeFunc? func) => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [func],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.EventsListener<_i19.RoomEvent> createListener(
          {bool? synchronized = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createListener,
          [],
          {#synchronized: synchronized},
        ),
        returnValue: _FakeEventsListener_6<_i19.RoomEvent>(
          this,
          Invocation.method(
            #createListener,
            [],
            {#synchronized: synchronized},
          ),
        ),
      ) as _i5.EventsListener<_i19.RoomEvent>);
}

/// A class which mocks [LocalParticipant].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalParticipant extends _i1.Mock implements _i23.LocalParticipant {
  MockLocalParticipant() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.LocalTrackPublication<_i24.LocalVideoTrack>>
      get videoTrackPublications => (super.noSuchMethod(
            Invocation.getter(#videoTrackPublications),
            returnValue: <_i9.LocalTrackPublication<_i24.LocalVideoTrack>>[],
          ) as List<_i9.LocalTrackPublication<_i24.LocalVideoTrack>>);

  @override
  List<_i9.LocalTrackPublication<_i25.LocalAudioTrack>>
      get audioTrackPublications => (super.noSuchMethod(
            Invocation.getter(#audioTrackPublications),
            returnValue: <_i9.LocalTrackPublication<_i25.LocalAudioTrack>>[],
          ) as List<_i9.LocalTrackPublication<_i25.LocalAudioTrack>>);

  @override
  _i6.Room get room => (super.noSuchMethod(
        Invocation.getter(#room),
        returnValue: _FakeRoom_7(
          this,
          Invocation.getter(#room),
        ),
      ) as _i6.Room);

  @override
  Map<String, _i9.LocalTrackPublication<_i8.LocalTrack>>
      get trackPublications => (super.noSuchMethod(
            Invocation.getter(#trackPublications),
            returnValue: <String, _i9.LocalTrackPublication<_i8.LocalTrack>>{},
          ) as Map<String, _i9.LocalTrackPublication<_i8.LocalTrack>>);

  @override
  double get audioLevel => (super.noSuchMethod(
        Invocation.getter(#audioLevel),
        returnValue: 0.0,
      ) as double);

  @override
  set audioLevel(double? _audioLevel) => super.noSuchMethod(
        Invocation.setter(
          #audioLevel,
          _audioLevel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get sid => (super.noSuchMethod(
        Invocation.getter(#sid),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.getter(#sid),
        ),
      ) as String);

  @override
  set sid(String? _sid) => super.noSuchMethod(
        Invocation.setter(
          #sid,
          _sid,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get identity => (super.noSuchMethod(
        Invocation.getter(#identity),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.getter(#identity),
        ),
      ) as String);

  @override
  set identity(String? _identity) => super.noSuchMethod(
        Invocation.setter(
          #identity,
          _identity,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set metadata(String? _metadata) => super.noSuchMethod(
        Invocation.setter(
          #metadata,
          _metadata,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastSpokeAt(DateTime? _lastSpokeAt) => super.noSuchMethod(
        Invocation.setter(
          #lastSpokeAt,
          _lastSpokeAt,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i12.ParticipantKind get kind => (super.noSuchMethod(
        Invocation.getter(#kind),
        returnValue: _i12.ParticipantKind.STANDARD,
      ) as _i12.ParticipantKind);

  @override
  _i7.ParticipantPermissions get permissions => (super.noSuchMethod(
        Invocation.getter(#permissions),
        returnValue: _FakeParticipantPermissions_8(
          this,
          Invocation.getter(#permissions),
        ),
      ) as _i7.ParticipantPermissions);

  @override
  _i4.UnmodifiableMapView<String, String> get attributes => (super.noSuchMethod(
        Invocation.getter(#attributes),
        returnValue: _FakeUnmodifiableMapView_3<String, String>(
          this,
          Invocation.getter(#attributes),
        ),
      ) as _i4.UnmodifiableMapView<String, String>);

  @override
  _i27.ParticipantState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i27.ParticipantState.joining,
      ) as _i27.ParticipantState);

  @override
  DateTime get joinedAt => (super.noSuchMethod(
        Invocation.getter(#joinedAt),
        returnValue: _FakeDateTime_9(
          this,
          Invocation.getter(#joinedAt),
        ),
      ) as DateTime);

  @override
  bool get isSpeaking => (super.noSuchMethod(
        Invocation.getter(#isSpeaking),
        returnValue: false,
      ) as bool);

  @override
  bool get isMuted => (super.noSuchMethod(
        Invocation.getter(#isMuted),
        returnValue: false,
      ) as bool);

  @override
  bool get hasAudio => (super.noSuchMethod(
        Invocation.getter(#hasAudio),
        returnValue: false,
      ) as bool);

  @override
  bool get hasVideo => (super.noSuchMethod(
        Invocation.getter(#hasVideo),
        returnValue: false,
      ) as bool);

  @override
  _i12.ConnectionQuality get connectionQuality => (super.noSuchMethod(
        Invocation.getter(#connectionQuality),
        returnValue: _i12.ConnectionQuality.unknown,
      ) as _i12.ConnectionQuality);

  @override
  _i28.EncryptionType get firstTrackEncryptionType => (super.noSuchMethod(
        Invocation.getter(#firstTrackEncryptionType),
        returnValue: _i28.EncryptionType.kNone,
      ) as _i28.EncryptionType);

  @override
  bool get isEncrypted => (super.noSuchMethod(
        Invocation.getter(#isEncrypted),
        returnValue: false,
      ) as bool);

  @override
  bool get hasInfo => (super.noSuchMethod(
        Invocation.getter(#hasInfo),
        returnValue: false,
      ) as bool);

  @override
  set isSpeaking(bool? speaking) => super.noSuchMethod(
        Invocation.setter(
          #isSpeaking,
          speaking,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  int get disposeFuncCount => (super.noSuchMethod(
        Invocation.getter(#disposeFuncCount),
        returnValue: 0,
      ) as int);

  @override
  _i5.EventsEmitter<_i19.ParticipantEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _FakeEventsEmitter_5<_i19.ParticipantEvent>(
          this,
          Invocation.getter(#events),
        ),
      ) as _i5.EventsEmitter<_i19.ParticipantEvent>);

  @override
  _i20.Future<
      _i9.LocalTrackPublication<_i25.LocalAudioTrack>> publishAudioTrack(
    _i25.LocalAudioTrack? track, {
    _i3.AudioPublishOptions? publishOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishAudioTrack,
          [track],
          {#publishOptions: publishOptions},
        ),
        returnValue:
            _i20.Future<_i9.LocalTrackPublication<_i25.LocalAudioTrack>>.value(
                _FakeLocalTrackPublication_10<_i25.LocalAudioTrack>(
          this,
          Invocation.method(
            #publishAudioTrack,
            [track],
            {#publishOptions: publishOptions},
          ),
        )),
      ) as _i20.Future<_i9.LocalTrackPublication<_i25.LocalAudioTrack>>);

  @override
  _i20.Future<
      _i9.LocalTrackPublication<_i24.LocalVideoTrack>> publishVideoTrack(
    _i24.LocalVideoTrack? track, {
    _i3.VideoPublishOptions? publishOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishVideoTrack,
          [track],
          {#publishOptions: publishOptions},
        ),
        returnValue:
            _i20.Future<_i9.LocalTrackPublication<_i24.LocalVideoTrack>>.value(
                _FakeLocalTrackPublication_10<_i24.LocalVideoTrack>(
          this,
          Invocation.method(
            #publishVideoTrack,
            [track],
            {#publishOptions: publishOptions},
          ),
        )),
      ) as _i20.Future<_i9.LocalTrackPublication<_i24.LocalVideoTrack>>);

  @override
  _i20.Future<void> removePublishedTrack(
    String? trackSid, {
    bool? notify = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePublishedTrack,
          [trackSid],
          {#notify: notify},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i3.DegradationPreference getDefaultDegradationPreference(
          _i24.LocalVideoTrack? track) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultDegradationPreference,
          [track],
        ),
        returnValue: _i3.DegradationPreference.disabled,
      ) as _i3.DegradationPreference);

  @override
  _i20.Future<void> unpublishAllTracks({
    bool? notify = true,
    bool? stopOnUnpublish,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unpublishAllTracks,
          [],
          {
            #notify: notify,
            #stopOnUnpublish: stopOnUnpublish,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> rePublishAllTracks() => (super.noSuchMethod(
        Invocation.method(
          #rePublishAllTracks,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> publishData(
    List<int>? data, {
    bool? reliable,
    List<String>? destinationIdentities,
    String? topic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishData,
          [data],
          {
            #reliable: reliable,
            #destinationIdentities: destinationIdentities,
            #topic: topic,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void setMetadata(String? metadata) => super.noSuchMethod(
        Invocation.method(
          #setMetadata,
          [metadata],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAttributes(Map<String, String>? attributes) => super.noSuchMethod(
        Invocation.method(
          #setAttributes,
          [attributes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setName(String? name) => super.noSuchMethod(
        Invocation.method(
          #setName,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.LocalTrackPublication<_i8.LocalTrack>? getTrackPublicationByName(
          String? name) =>
      (super.noSuchMethod(Invocation.method(
        #getTrackPublicationByName,
        [name],
      )) as _i9.LocalTrackPublication<_i8.LocalTrack>?);

  @override
  _i9.LocalTrackPublication<_i8.LocalTrack>? getTrackPublicationBySid(
          String? sid) =>
      (super.noSuchMethod(Invocation.method(
        #getTrackPublicationBySid,
        [sid],
      )) as _i9.LocalTrackPublication<_i8.LocalTrack>?);

  @override
  _i9.LocalTrackPublication<_i8.LocalTrack>? getTrackPublicationBySource(
          _i12.TrackSource? source) =>
      (super.noSuchMethod(Invocation.method(
        #getTrackPublicationBySource,
        [source],
      )) as _i9.LocalTrackPublication<_i8.LocalTrack>?);

  @override
  _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?> setCameraEnabled(
    bool? enabled, {
    _i29.CameraCaptureOptions? cameraCaptureOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCameraEnabled,
          [enabled],
          {#cameraCaptureOptions: cameraCaptureOptions},
        ),
        returnValue:
            _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?>.value(),
      ) as _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?>);

  @override
  _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?> setMicrophoneEnabled(
    bool? enabled, {
    _i29.AudioCaptureOptions? audioCaptureOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMicrophoneEnabled,
          [enabled],
          {#audioCaptureOptions: audioCaptureOptions},
        ),
        returnValue:
            _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?>.value(),
      ) as _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?>);

  @override
  _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?> setScreenShareEnabled(
    bool? enabled, {
    bool? captureScreenAudio,
    _i29.ScreenShareCaptureOptions? screenShareCaptureOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setScreenShareEnabled,
          [enabled],
          {
            #captureScreenAudio: captureScreenAudio,
            #screenShareCaptureOptions: screenShareCaptureOptions,
          },
        ),
        returnValue:
            _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?>.value(),
      ) as _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?>);

  @override
  _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?> setSourceEnabled(
    _i12.TrackSource? source,
    bool? enabled, {
    bool? captureScreenAudio,
    _i29.AudioCaptureOptions? audioCaptureOptions,
    _i29.CameraCaptureOptions? cameraCaptureOptions,
    _i29.ScreenShareCaptureOptions? screenShareCaptureOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSourceEnabled,
          [
            source,
            enabled,
          ],
          {
            #captureScreenAudio: captureScreenAudio,
            #audioCaptureOptions: audioCaptureOptions,
            #cameraCaptureOptions: cameraCaptureOptions,
            #screenShareCaptureOptions: screenShareCaptureOptions,
          },
        ),
        returnValue:
            _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?>.value(),
      ) as _i20.Future<_i9.LocalTrackPublication<_i8.LocalTrack>?>);

  @override
  void setTrackSubscriptionPermissions({
    required bool? allParticipantsAllowed,
    List<_i12.ParticipantTrackPermission>? trackPermissions = const [],
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setTrackSubscriptionPermissions,
          [],
          {
            #allParticipantsAllowed: allParticipantsAllowed,
            #trackPermissions: trackPermissions,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendTrackSubscriptionPermissions() => super.noSuchMethod(
        Invocation.method(
          #sendTrackSubscriptionPermissions,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Iterable<_i30.TrackPublishedResponse> publishedTracksInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #publishedTracksInfo,
          [],
        ),
        returnValue: <_i30.TrackPublishedResponse>[],
      ) as Iterable<_i30.TrackPublishedResponse>);

  @override
  _i7.ParticipantPermissions? setPermissions(
          _i7.ParticipantPermissions? newValue) =>
      (super.noSuchMethod(Invocation.method(
        #setPermissions,
        [newValue],
      )) as _i7.ParticipantPermissions?);

  @override
  _i20.Future<void> publishAdditionalCodecForPublication(
    _i9.LocalTrackPublication<_i8.LocalTrack>? publication,
    String? backupCodec,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishAdditionalCodecForPublication,
          [
            publication,
            backupCodec,
          ],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void updateConnectionQuality(_i12.ConnectionQuality? quality) =>
      super.noSuchMethod(
        Invocation.method(
          #updateConnectionQuality,
          [quality],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<bool> updateFromInfo(_i10.ParticipantInfo? info) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFromInfo,
          [info],
        ),
        returnValue: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  void updateName(String? name) => super.noSuchMethod(
        Invocation.method(
          #updateName,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addTrackPublication(_i9.LocalTrackPublication<_i8.LocalTrack>? pub) =>
      super.noSuchMethod(
        Invocation.method(
          #addTrackPublication,
          [pub],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i9.LocalTrackPublication<_i8.LocalTrack>> getTrackPublications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrackPublications,
          [],
        ),
        returnValue: <_i9.LocalTrackPublication<_i8.LocalTrack>>[],
      ) as List<_i9.LocalTrackPublication<_i8.LocalTrack>>);

  @override
  bool isCameraEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isCameraEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isMicrophoneEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isMicrophoneEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isScreenShareEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isScreenShareEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isScreenShareAudioEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isScreenShareAudioEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i20.Future<bool> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  void addListener(_i21.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i21.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose(_i22.OnDisposeFunc? func) => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [func],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.EventsListener<_i19.ParticipantEvent> createListener(
          {bool? synchronized = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createListener,
          [],
          {#synchronized: synchronized},
        ),
        returnValue: _FakeEventsListener_6<_i19.ParticipantEvent>(
          this,
          Invocation.method(
            #createListener,
            [],
            {#synchronized: synchronized},
          ),
        ),
      ) as _i5.EventsListener<_i19.ParticipantEvent>);
}

/// A class which mocks [RemoteParticipant].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteParticipant extends _i1.Mock implements _i13.RemoteParticipant {
  MockRemoteParticipant() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i31.RemoteTrackPublication<_i32.RemoteVideoTrack>>
      get videoTrackPublications => (super.noSuchMethod(
            Invocation.getter(#videoTrackPublications),
            returnValue: <_i31.RemoteTrackPublication<_i32.RemoteVideoTrack>>[],
          ) as List<_i31.RemoteTrackPublication<_i32.RemoteVideoTrack>>);

  @override
  List<_i31.RemoteTrackPublication<_i33.RemoteAudioTrack>>
      get audioTrackPublications => (super.noSuchMethod(
            Invocation.getter(#audioTrackPublications),
            returnValue: <_i31.RemoteTrackPublication<_i33.RemoteAudioTrack>>[],
          ) as List<_i31.RemoteTrackPublication<_i33.RemoteAudioTrack>>);

  @override
  List<_i31.RemoteTrackPublication<_i34.RemoteTrack>> get subscribedTracks =>
      (super.noSuchMethod(
        Invocation.getter(#subscribedTracks),
        returnValue: <_i31.RemoteTrackPublication<_i34.RemoteTrack>>[],
      ) as List<_i31.RemoteTrackPublication<_i34.RemoteTrack>>);

  @override
  _i6.Room get room => (super.noSuchMethod(
        Invocation.getter(#room),
        returnValue: _FakeRoom_7(
          this,
          Invocation.getter(#room),
        ),
      ) as _i6.Room);

  @override
  Map<String, _i31.RemoteTrackPublication<_i34.RemoteTrack>>
      get trackPublications => (super.noSuchMethod(
            Invocation.getter(#trackPublications),
            returnValue: <String,
                _i31.RemoteTrackPublication<_i34.RemoteTrack>>{},
          ) as Map<String, _i31.RemoteTrackPublication<_i34.RemoteTrack>>);

  @override
  double get audioLevel => (super.noSuchMethod(
        Invocation.getter(#audioLevel),
        returnValue: 0.0,
      ) as double);

  @override
  set audioLevel(double? _audioLevel) => super.noSuchMethod(
        Invocation.setter(
          #audioLevel,
          _audioLevel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get sid => (super.noSuchMethod(
        Invocation.getter(#sid),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.getter(#sid),
        ),
      ) as String);

  @override
  set sid(String? _sid) => super.noSuchMethod(
        Invocation.setter(
          #sid,
          _sid,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get identity => (super.noSuchMethod(
        Invocation.getter(#identity),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.getter(#identity),
        ),
      ) as String);

  @override
  set identity(String? _identity) => super.noSuchMethod(
        Invocation.setter(
          #identity,
          _identity,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set metadata(String? _metadata) => super.noSuchMethod(
        Invocation.setter(
          #metadata,
          _metadata,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set lastSpokeAt(DateTime? _lastSpokeAt) => super.noSuchMethod(
        Invocation.setter(
          #lastSpokeAt,
          _lastSpokeAt,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i12.ParticipantKind get kind => (super.noSuchMethod(
        Invocation.getter(#kind),
        returnValue: _i12.ParticipantKind.STANDARD,
      ) as _i12.ParticipantKind);

  @override
  _i7.ParticipantPermissions get permissions => (super.noSuchMethod(
        Invocation.getter(#permissions),
        returnValue: _FakeParticipantPermissions_8(
          this,
          Invocation.getter(#permissions),
        ),
      ) as _i7.ParticipantPermissions);

  @override
  _i4.UnmodifiableMapView<String, String> get attributes => (super.noSuchMethod(
        Invocation.getter(#attributes),
        returnValue: _FakeUnmodifiableMapView_3<String, String>(
          this,
          Invocation.getter(#attributes),
        ),
      ) as _i4.UnmodifiableMapView<String, String>);

  @override
  _i27.ParticipantState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i27.ParticipantState.joining,
      ) as _i27.ParticipantState);

  @override
  DateTime get joinedAt => (super.noSuchMethod(
        Invocation.getter(#joinedAt),
        returnValue: _FakeDateTime_9(
          this,
          Invocation.getter(#joinedAt),
        ),
      ) as DateTime);

  @override
  bool get isSpeaking => (super.noSuchMethod(
        Invocation.getter(#isSpeaking),
        returnValue: false,
      ) as bool);

  @override
  bool get isMuted => (super.noSuchMethod(
        Invocation.getter(#isMuted),
        returnValue: false,
      ) as bool);

  @override
  bool get hasAudio => (super.noSuchMethod(
        Invocation.getter(#hasAudio),
        returnValue: false,
      ) as bool);

  @override
  bool get hasVideo => (super.noSuchMethod(
        Invocation.getter(#hasVideo),
        returnValue: false,
      ) as bool);

  @override
  _i12.ConnectionQuality get connectionQuality => (super.noSuchMethod(
        Invocation.getter(#connectionQuality),
        returnValue: _i12.ConnectionQuality.unknown,
      ) as _i12.ConnectionQuality);

  @override
  _i28.EncryptionType get firstTrackEncryptionType => (super.noSuchMethod(
        Invocation.getter(#firstTrackEncryptionType),
        returnValue: _i28.EncryptionType.kNone,
      ) as _i28.EncryptionType);

  @override
  bool get isEncrypted => (super.noSuchMethod(
        Invocation.getter(#isEncrypted),
        returnValue: false,
      ) as bool);

  @override
  bool get hasInfo => (super.noSuchMethod(
        Invocation.getter(#hasInfo),
        returnValue: false,
      ) as bool);

  @override
  set isSpeaking(bool? speaking) => super.noSuchMethod(
        Invocation.setter(
          #isSpeaking,
          speaking,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  int get disposeFuncCount => (super.noSuchMethod(
        Invocation.getter(#disposeFuncCount),
        returnValue: 0,
      ) as int);

  @override
  _i5.EventsEmitter<_i19.ParticipantEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _FakeEventsEmitter_5<_i19.ParticipantEvent>(
          this,
          Invocation.getter(#events),
        ),
      ) as _i5.EventsEmitter<_i19.ParticipantEvent>);

  @override
  _i31.RemoteTrackPublication<_i34.RemoteTrack>? getTrackPublicationByName(
          String? name) =>
      (super.noSuchMethod(Invocation.method(
        #getTrackPublicationByName,
        [name],
      )) as _i31.RemoteTrackPublication<_i34.RemoteTrack>?);

  @override
  _i31.RemoteTrackPublication<_i34.RemoteTrack>? getTrackPublicationBySid(
          String? sid) =>
      (super.noSuchMethod(Invocation.method(
        #getTrackPublicationBySid,
        [sid],
      )) as _i31.RemoteTrackPublication<_i34.RemoteTrack>?);

  @override
  _i31.RemoteTrackPublication<_i34.RemoteTrack>? getTrackPublicationBySource(
          _i12.TrackSource? source) =>
      (super.noSuchMethod(Invocation.method(
        #getTrackPublicationBySource,
        [source],
      )) as _i31.RemoteTrackPublication<_i34.RemoteTrack>?);

  @override
  _i20.Future<void> addSubscribedMediaTrack(
    _i11.MediaStreamTrack? mediaTrack,
    _i11.MediaStream? stream,
    String? trackSid, {
    _i11.RTCRtpReceiver? receiver,
    _i29.AudioOutputOptions? audioOutputOptions =
        const _i29.AudioOutputOptions(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSubscribedMediaTrack,
          [
            mediaTrack,
            stream,
            trackSid,
          ],
          {
            #receiver: receiver,
            #audioOutputOptions: audioOutputOptions,
          },
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<bool> updateFromInfo(_i10.ParticipantInfo? info) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFromInfo,
          [info],
        ),
        returnValue: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  _i20.Future<void> removePublishedTrack(
    String? trackSid, {
    bool? notify = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #removePublishedTrack,
          [trackSid],
          {#notify: notify},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> removeAllPublishedTracks({bool? notify = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAllPublishedTracks,
          [],
          {#notify: notify},
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i10.ParticipantTracks participantTracks() => (super.noSuchMethod(
        Invocation.method(
          #participantTracks,
          [],
        ),
        returnValue: _FakeParticipantTracks_11(
          this,
          Invocation.method(
            #participantTracks,
            [],
          ),
        ),
      ) as _i10.ParticipantTracks);

  @override
  void updateConnectionQuality(_i12.ConnectionQuality? quality) =>
      super.noSuchMethod(
        Invocation.method(
          #updateConnectionQuality,
          [quality],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.ParticipantPermissions? setPermissions(
          _i7.ParticipantPermissions? newValue) =>
      (super.noSuchMethod(Invocation.method(
        #setPermissions,
        [newValue],
      )) as _i7.ParticipantPermissions?);

  @override
  void updateName(String? name) => super.noSuchMethod(
        Invocation.method(
          #updateName,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addTrackPublication(
          _i31.RemoteTrackPublication<_i34.RemoteTrack>? pub) =>
      super.noSuchMethod(
        Invocation.method(
          #addTrackPublication,
          [pub],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i31.RemoteTrackPublication<_i34.RemoteTrack>> getTrackPublications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrackPublications,
          [],
        ),
        returnValue: <_i31.RemoteTrackPublication<_i34.RemoteTrack>>[],
      ) as List<_i31.RemoteTrackPublication<_i34.RemoteTrack>>);

  @override
  bool isCameraEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isCameraEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isMicrophoneEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isMicrophoneEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isScreenShareEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isScreenShareEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isScreenShareAudioEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isScreenShareAudioEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i20.Future<bool> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  void addListener(_i21.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i21.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose(_i22.OnDisposeFunc? func) => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [func],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.EventsListener<_i19.ParticipantEvent> createListener(
          {bool? synchronized = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createListener,
          [],
          {#synchronized: synchronized},
        ),
        returnValue: _FakeEventsListener_6<_i19.ParticipantEvent>(
          this,
          Invocation.method(
            #createListener,
            [],
            {#synchronized: synchronized},
          ),
        ),
      ) as _i5.EventsListener<_i19.ParticipantEvent>);
}

/// A class which mocks [Track].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrack extends _i1.Mock implements _i16.Track {
  MockTrack() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.TrackType get kind => (super.noSuchMethod(
        Invocation.getter(#kind),
        returnValue: _i12.TrackType.AUDIO,
      ) as _i12.TrackType);

  @override
  _i12.TrackSource get source => (super.noSuchMethod(
        Invocation.getter(#source),
        returnValue: _i12.TrackSource.unknown,
      ) as _i12.TrackSource);

  @override
  set sid(String? _sid) => super.noSuchMethod(
        Invocation.setter(
          #sid,
          _sid,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set transceiver(_i11.RTCRtpTransceiver? _transceiver) => super.noSuchMethod(
        Invocation.setter(
          #transceiver,
          _transceiver,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set receiver(_i11.RTCRtpReceiver? _receiver) => super.noSuchMethod(
        Invocation.setter(
          #receiver,
          _receiver,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.MediaStream get mediaStream => (super.noSuchMethod(
        Invocation.getter(#mediaStream),
        returnValue: _FakeMediaStream_12(
          this,
          Invocation.getter(#mediaStream),
        ),
      ) as _i11.MediaStream);

  @override
  _i11.MediaStreamTrack get mediaStreamTrack => (super.noSuchMethod(
        Invocation.getter(#mediaStreamTrack),
        returnValue: _FakeMediaStreamTrack_13(
          this,
          Invocation.getter(#mediaStreamTrack),
        ),
      ) as _i11.MediaStreamTrack);

  @override
  bool get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: false,
      ) as bool);

  @override
  bool get muted => (super.noSuchMethod(
        Invocation.getter(#muted),
        returnValue: false,
      ) as bool);

  @override
  _i11.RTCRtpMediaType get mediaType => (super.noSuchMethod(
        Invocation.getter(#mediaType),
        returnValue: _i11.RTCRtpMediaType.RTCRtpMediaTypeAudio,
      ) as _i11.RTCRtpMediaType);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  int get disposeFuncCount => (super.noSuchMethod(
        Invocation.getter(#disposeFuncCount),
        returnValue: 0,
      ) as int);

  @override
  _i5.EventsEmitter<_i19.TrackEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _FakeEventsEmitter_5<_i19.TrackEvent>(
          this,
          Invocation.getter(#events),
        ),
      ) as _i5.EventsEmitter<_i19.TrackEvent>);

  @override
  String getCid() => (super.noSuchMethod(
        Invocation.method(
          #getCid,
          [],
        ),
        returnValue: _i26.dummyValue<String>(
          this,
          Invocation.method(
            #getCid,
            [],
          ),
        ),
      ) as String);

  @override
  _i20.Future<bool> start() => (super.noSuchMethod(
        Invocation.method(
          #start,
          [],
        ),
        returnValue: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  _i20.Future<bool> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  _i20.Future<void> enable() => (super.noSuchMethod(
        Invocation.method(
          #enable,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> disable() => (super.noSuchMethod(
        Invocation.method(
          #disable,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<bool> monitorStats() => (super.noSuchMethod(
        Invocation.method(
          #monitorStats,
          [],
        ),
        returnValue: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  _i20.Future<void> onStarted() => (super.noSuchMethod(
        Invocation.method(
          #onStarted,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  _i20.Future<void> onStopped() => (super.noSuchMethod(
        Invocation.method(
          #onStopped,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);

  @override
  void startMonitor() => super.noSuchMethod(
        Invocation.method(
          #startMonitor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopMonitor() => super.noSuchMethod(
        Invocation.method(
          #stopMonitor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateMuted(
    bool? muted, {
    bool? shouldNotify = true,
    bool? shouldSendSignal = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateMuted,
          [muted],
          {
            #shouldNotify: shouldNotify,
            #shouldSendSignal: shouldSendSignal,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateMediaStreamAndTrack(
    _i11.MediaStream? stream,
    _i11.MediaStreamTrack? track,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateMediaStreamAndTrack,
          [
            stream,
            track,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProcessedTrack(_i11.MediaStreamTrack? track) => super.noSuchMethod(
        Invocation.method(
          #setProcessedTrack,
          [track],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i20.Future<bool> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i20.Future<bool>.value(false),
      ) as _i20.Future<bool>);

  @override
  void addListener(_i21.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i21.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose(_i22.OnDisposeFunc? func) => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [func],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.EventsListener<_i19.TrackEvent> createListener(
          {bool? synchronized = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createListener,
          [],
          {#synchronized: synchronized},
        ),
        returnValue: _FakeEventsListener_6<_i19.TrackEvent>(
          this,
          Invocation.method(
            #createListener,
            [],
            {#synchronized: synchronized},
          ),
        ),
      ) as _i5.EventsListener<_i19.TrackEvent>);
}
