// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB56i9YDqv1iFXQSU2eo8F1C_oPfSIwQIA',
    appId: '1:18237618385:web:e1315ba20f3c458852edf0',
    messagingSenderId: '18237618385',
    projectId: 'arena-flutter',
    authDomain: 'arena-flutter.firebaseapp.com',
    storageBucket: 'arena-flutter.firebasestorage.app',
    measurementId: 'G-X7TPEVK94P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56i9YDqv1iFXQSU2eo8F1C_oPfSIwQIA',
    appId: '1:18237618385:android:010406bf45cc714852edf0',
    messagingSenderId: '18237618385',
    projectId: 'arena-flutter',
    storageBucket: 'arena-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB56i9YDqv1iFXQSU2eo8F1C_oPfSIwQIA',
    appId: '1:18237618385:ios:159de79359b3a43e52edf0',
    messagingSenderId: '18237618385',
    projectId: 'arena-flutter',
    storageBucket: 'arena-flutter.firebasestorage.app',
    iosBundleId: 'com.example.arena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB56i9YDqv1iFXQSU2eo8F1C_oPfSIwQIA',
    appId: '1:18237618385:ios:159de79359b3a43e52edf0',
    messagingSenderId: '18237618385',
    projectId: 'arena-flutter',
    storageBucket: 'arena-flutter.firebasestorage.app',
    iosBundleId: 'com.example.arena',
  );
} 