// Mocks generated by Mockito 5.4.4 from annotations
// in arena/test/screens/arena_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;
import 'dart:ui' as _i12;

import 'package:appwrite/appwrite.dart' as _i2;
import 'package:appwrite/models.dart' as _i3;
import 'package:arena/models/gift_transaction.dart' as _i9;
import 'package:arena/models/user_profile.dart' as _i6;
import 'package:arena/services/appwrite_service.dart' as _i4;
import 'package:arena/services/livekit_service.dart' as _i10;
import 'package:livekit_client/livekit_client.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccount_1 extends _i1.SmartFake implements _i2.Account {
  _FakeAccount_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabases_2 extends _i1.SmartFake implements _i2.Databases {
  _FakeDatabases_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorage_3 extends _i1.SmartFake implements _i2.Storage {
  _FakeStorage_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtime_4 extends _i1.SmartFake implements _i2.Realtime {
  _FakeRealtime_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctions_5 extends _i1.SmartFake implements _i2.Functions {
  _FakeFunctions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_6 extends _i1.SmartFake implements _i3.User {
  _FakeUser_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSession_7 extends _i1.SmartFake implements _i3.Session {
  _FakeSession_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeSubscription_8 extends _i1.SmartFake
    implements _i2.RealtimeSubscription {
  _FakeRealtimeSubscription_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppwriteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppwriteService extends _i1.Mock implements _i4.AppwriteService {
  MockAppwriteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  set client(_i2.Client? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Account get account => (super.noSuchMethod(
        Invocation.getter(#account),
        returnValue: _FakeAccount_1(
          this,
          Invocation.getter(#account),
        ),
      ) as _i2.Account);

  @override
  set account(_i2.Account? _account) => super.noSuchMethod(
        Invocation.setter(
          #account,
          _account,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Databases get databases => (super.noSuchMethod(
        Invocation.getter(#databases),
        returnValue: _FakeDatabases_2(
          this,
          Invocation.getter(#databases),
        ),
      ) as _i2.Databases);

  @override
  set databases(_i2.Databases? _databases) => super.noSuchMethod(
        Invocation.setter(
          #databases,
          _databases,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Storage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeStorage_3(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i2.Storage);

  @override
  set storage(_i2.Storage? _storage) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          _storage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Realtime get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtime_4(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i2.Realtime);

  @override
  set realtime(_i2.Realtime? _realtime) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          _realtime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Functions get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFunctions_5(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i2.Functions);

  @override
  set functions(_i2.Functions? _functions) => super.noSuchMethod(
        Invocation.setter(
          #functions,
          _functions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Realtime get realtimeInstance => (super.noSuchMethod(
        Invocation.getter(#realtimeInstance),
        returnValue: _FakeRealtime_4(
          this,
          Invocation.getter(#realtimeInstance),
        ),
      ) as _i2.Realtime);

  @override
  _i5.Future<void> debugAppwriteConnection() => (super.noSuchMethod(
        Invocation.method(
          #debugAppwriteConnection,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> debugUserProfileLoading(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #debugUserProfileLoading,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.User> createAccount({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [],
          {
            #email: email,
            #password: password,
            #name: name,
          },
        ),
        returnValue: _i5.Future<_i3.User>.value(_FakeUser_6(
          this,
          Invocation.method(
            #createAccount,
            [],
            {
              #email: email,
              #password: password,
              #name: name,
            },
          ),
        )),
      ) as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.Session> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i3.Session>.value(_FakeSession_7(
          this,
          Invocation.method(
            #signIn,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i3.Session>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendPasswordResetEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Session> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<_i3.Session>.value(_FakeSession_7(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Session>);

  @override
  _i5.Future<_i3.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i3.User?>.value(),
      ) as _i5.Future<_i3.User?>);

  @override
  _i5.Future<void> createUserProfile({
    required String? userId,
    required String? name,
    required String? email,
    String? bio,
    String? avatar,
    String? location,
    String? website,
    String? xHandle,
    String? linkedinHandle,
    String? youtubeHandle,
    String? facebookHandle,
    String? instagramHandle,
    List<String>? interests,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserProfile,
          [],
          {
            #userId: userId,
            #name: name,
            #email: email,
            #bio: bio,
            #avatar: avatar,
            #location: location,
            #website: website,
            #xHandle: xHandle,
            #linkedinHandle: linkedinHandle,
            #youtubeHandle: youtubeHandle,
            #facebookHandle: facebookHandle,
            #instagramHandle: instagramHandle,
            #interests: interests,
            #metadata: metadata,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.UserProfile?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i5.Future<_i6.UserProfile?>.value(),
      ) as _i5.Future<_i6.UserProfile?>);

  @override
  _i5.Future<void> updateUserProfile({
    required String? userId,
    String? name,
    String? bio,
    String? avatar,
    String? location,
    String? website,
    String? xHandle,
    String? linkedinHandle,
    String? youtubeHandle,
    String? facebookHandle,
    String? instagramHandle,
    List<String>? interests,
    bool? isPublicProfile,
    bool? isAvailableAsModerator,
    bool? isAvailableAsJudge,
    int? coinBalance,
    int? totalGiftsSent,
    int? totalGiftsReceived,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #userId: userId,
            #name: name,
            #bio: bio,
            #avatar: avatar,
            #location: location,
            #website: website,
            #xHandle: xHandle,
            #linkedinHandle: linkedinHandle,
            #youtubeHandle: youtubeHandle,
            #facebookHandle: facebookHandle,
            #instagramHandle: instagramHandle,
            #interests: interests,
            #isPublicProfile: isPublicProfile,
            #isAvailableAsModerator: isAvailableAsModerator,
            #isAvailableAsJudge: isAvailableAsJudge,
            #coinBalance: coinBalance,
            #totalGiftsSent: totalGiftsSent,
            #totalGiftsReceived: totalGiftsReceived,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateUserStats({
    required String? userId,
    int? reputation,
    int? totalDebates,
    int? totalWins,
    int? totalRoomsCreated,
    int? totalRoomsJoined,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserStats,
          [],
          {
            #userId: userId,
            #reputation: reputation,
            #totalDebates: totalDebates,
            #totalWins: totalWins,
            #totalRoomsCreated: totalRoomsCreated,
            #totalRoomsJoined: totalRoomsJoined,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> uploadAvatar({
    required String? userId,
    required _i7.Uint8List? fileBytes,
    required String? fileName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [],
          {
            #userId: userId,
            #fileBytes: fileBytes,
            #fileName: fileName,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> deleteAvatar(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAvatar,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createDebateClub({
    required String? name,
    required String? description,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDebateClub,
          [],
          {
            #name: name,
            #description: description,
            #createdBy: createdBy,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getDebateClubs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDebateClubs,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> joinDebateClub({
    required String? clubId,
    required String? userId,
    required String? username,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinDebateClub,
          [],
          {
            #clubId: clubId,
            #userId: userId,
            #username: username,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> leaveDebateClub({
    required String? clubId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveDebateClub,
          [],
          {
            #clubId: clubId,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createMembership({
    required String? userId,
    required String? clubId,
    String? role = r'member',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMembership,
          [],
          {
            #userId: userId,
            #clubId: clubId,
            #role: role,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getUserMemberships(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserMemberships,
          [userId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getClubMembers(String? clubId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClubMembers,
          [clubId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> updateMembershipRole({
    required String? membershipId,
    required String? newRole,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMembershipRole,
          [],
          {
            #membershipId: membershipId,
            #newRole: newRole,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteMembership(String? membershipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMembership,
          [membershipId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> createRoom({
    required String? title,
    required String? description,
    required String? createdBy,
    List<String>? tags,
    int? maxParticipants = 999999,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRoom,
          [],
          {
            #title: title,
            #description: description,
            #createdBy: createdBy,
            #tags: tags,
            #maxParticipants: maxParticipants,
          },
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createRoom,
            [],
            {
              #title: title,
              #description: description,
              #createdBy: createdBy,
              #tags: tags,
              #maxParticipants: maxParticipants,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createDiscussionRoom({
    required String? title,
    required String? description,
    required String? createdBy,
    required String? status,
    required bool? isPrivate,
    List<String>? tags,
    int? maxParticipants = 999999,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDiscussionRoom,
          [],
          {
            #title: title,
            #description: description,
            #createdBy: createdBy,
            #status: status,
            #isPrivate: isPrivate,
            #tags: tags,
            #maxParticipants: maxParticipants,
          },
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createDiscussionRoom,
            [],
            {
              #title: title,
              #description: description,
              #createdBy: createdBy,
              #status: status,
              #isPrivate: isPrivate,
              #tags: tags,
              #maxParticipants: maxParticipants,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getRooms() => (super.noSuchMethod(
        Invocation.method(
          #getRooms,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>?> getRoom(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoom,
          [roomId],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> joinRoom({
    required String? roomId,
    required String? userId,
    String? role = r'audience',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinRoom,
          [],
          {
            #roomId: roomId,
            #userId: userId,
            #role: role,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> joinDebateDiscussionRoom({
    required String? roomId,
    required String? userId,
    String? role = r'audience',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinDebateDiscussionRoom,
          [],
          {
            #roomId: roomId,
            #userId: userId,
            #role: role,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> leaveRoom({
    required String? roomId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveRoom,
          [],
          {
            #roomId: roomId,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateParticipantRole({
    required String? roomId,
    required String? userId,
    required String? newRole,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateParticipantRole,
          [],
          {
            #roomId: roomId,
            #userId: userId,
            #newRole: newRole,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateParticipantMetadata({
    required String? roomId,
    required String? userId,
    required Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateParticipantMetadata,
          [],
          {
            #roomId: roomId,
            #userId: userId,
            #metadata: metadata,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getUserRoomParticipation({
    required String? roomId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserRoomParticipation,
          [],
          {
            #roomId: roomId,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> deleteDebateClub(String? clubId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDebateClub,
          [clubId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> followUser({
    required String? followerId,
    required String? followingId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [],
          {
            #followerId: followerId,
            #followingId: followingId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unfollowUser({
    required String? followerId,
    required String? followingId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [],
          {
            #followerId: followerId,
            #followingId: followingId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isFollowing({
    required String? followerId,
    required String? followingId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFollowing,
          [],
          {
            #followerId: followerId,
            #followingId: followingId,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> getFollowerCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getFollowerCount,
          [userId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getFollowingCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getFollowingCount,
          [userId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i6.UserProfile>> getUserFollowing(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFollowing,
          [userId],
        ),
        returnValue:
            _i5.Future<List<_i6.UserProfile>>.value(<_i6.UserProfile>[]),
      ) as _i5.Future<List<_i6.UserProfile>>);

  @override
  _i5.Future<List<_i6.UserProfile>> getUserFollowers(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFollowers,
          [userId],
        ),
        returnValue:
            _i5.Future<List<_i6.UserProfile>>.value(<_i6.UserProfile>[]),
      ) as _i5.Future<List<_i6.UserProfile>>);

  @override
  _i5.Future<List<_i6.UserProfile>> getUserNetworkForArenaRoles(
    String? userId, {
    String? arenaRoomId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserNetworkForArenaRoles,
          [userId],
          {#arenaRoomId: arenaRoomId},
        ),
        returnValue:
            _i5.Future<List<_i6.UserProfile>>.value(<_i6.UserProfile>[]),
      ) as _i5.Future<List<_i6.UserProfile>>);

  @override
  _i5.Future<void> sendChallenge({
    required String? challengerId,
    required String? challengedId,
    required String? topic,
    String? description,
    required String? position,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendChallenge,
          [],
          {
            #challengerId: challengerId,
            #challengedId: challengedId,
            #topic: topic,
            #description: description,
            #position: position,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> respondToChallenge({
    required String? challengeId,
    required String? response,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #respondToChallenge,
          [],
          {
            #challengeId: challengeId,
            #response: response,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getUserChallenges(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserChallenges,
          [userId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getUserArenaRoleNotifications(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserArenaRoleNotifications,
          [userId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<String> createDebateDiscussionRoom({
    required String? name,
    required String? description,
    required String? category,
    required String? debateStyle,
    required String? createdBy,
    bool? isPrivate = false,
    String? password,
    bool? isScheduled = false,
    DateTime? scheduledDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDebateDiscussionRoom,
          [],
          {
            #name: name,
            #description: description,
            #category: category,
            #debateStyle: debateStyle,
            #createdBy: createdBy,
            #isPrivate: isPrivate,
            #password: password,
            #isScheduled: isScheduled,
            #scheduledDate: scheduledDate,
          },
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createDebateDiscussionRoom,
            [],
            {
              #name: name,
              #description: description,
              #category: category,
              #debateStyle: debateStyle,
              #createdBy: createdBy,
              #isPrivate: isPrivate,
              #password: password,
              #isScheduled: isScheduled,
              #scheduledDate: scheduledDate,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getDebateDiscussionRooms() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDebateDiscussionRooms,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getDebateDiscussionRoomsPaginated({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDebateDiscussionRoomsPaginated,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>?> getDebateDiscussionRoom(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDebateDiscussionRoom,
          [roomId],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<bool> validateDebateDiscussionRoomPassword({
    required String? roomId,
    required String? enteredPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateDebateDiscussionRoomPassword,
          [],
          {
            #roomId: roomId,
            #enteredPassword: enteredPassword,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> leaveDebateDiscussionRoom({
    required String? roomId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveDebateDiscussionRoom,
          [],
          {
            #roomId: roomId,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getDebateDiscussionParticipants(
          String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDebateDiscussionParticipants,
          [roomId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getDiscussionRoomParticipants(
          String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDiscussionRoomParticipants,
          [roomId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> cleanupIncorrectOpenDiscussionData() => (super.noSuchMethod(
        Invocation.method(
          #cleanupIncorrectOpenDiscussionData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateDebateDiscussionParticipantRole({
    required String? roomId,
    required String? userId,
    required String? newRole,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDebateDiscussionParticipantRole,
          [],
          {
            #roomId: roomId,
            #userId: userId,
            #newRole: newRole,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateRoomParticipantRole({
    required String? roomId,
    required String? userId,
    required String? newRole,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRoomParticipantRole,
          [],
          {
            #roomId: roomId,
            #userId: userId,
            #newRole: newRole,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateDebateDiscussionRoom({
    required String? roomId,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDebateDiscussionRoom,
          [],
          {
            #roomId: roomId,
            #data: data,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> createArenaRoom({
    required String? challengeId,
    required String? challengerId,
    required String? challengedId,
    required String? topic,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createArenaRoom,
          [],
          {
            #challengeId: challengeId,
            #challengerId: challengerId,
            #challengedId: challengedId,
            #topic: topic,
            #description: description,
          },
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createArenaRoom,
            [],
            {
              #challengeId: challengeId,
              #challengerId: challengerId,
              #challengedId: challengedId,
              #topic: topic,
              #description: description,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<Map<String, dynamic>?> getArenaRoom(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArenaRoom,
          [roomId],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> closeArenaRoom(String? roomId) => (super.noSuchMethod(
        Invocation.method(
          #closeArenaRoom,
          [roomId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> assignArenaRole({
    required String? roomId,
    required String? userId,
    required String? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignArenaRole,
          [],
          {
            #roomId: roomId,
            #userId: userId,
            #role: role,
          },
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #assignArenaRole,
            [],
            {
              #roomId: roomId,
              #userId: userId,
              #role: role,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getArenaParticipants(String? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArenaParticipants,
          [roomId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> updateArenaParticipantStatus({
    required String? roomId,
    required String? userId,
    bool? completedSelection,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArenaParticipantStatus,
          [],
          {
            #roomId: roomId,
            #userId: userId,
            #completedSelection: completedSelection,
            #metadata: metadata,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> submitArenaJudgment({
    required String? roomId,
    required String? judgeId,
    required String? challengeId,
    required double? affirmativeArguments,
    required double? affirmativePresentation,
    required double? affirmativeRebuttal,
    required double? negativeArguments,
    required double? negativePresentation,
    required double? negativeRebuttal,
    required String? winner,
    String? comments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitArenaJudgment,
          [],
          {
            #roomId: roomId,
            #judgeId: judgeId,
            #challengeId: challengeId,
            #affirmativeArguments: affirmativeArguments,
            #affirmativePresentation: affirmativePresentation,
            #affirmativeRebuttal: affirmativeRebuttal,
            #negativeArguments: negativeArguments,
            #negativePresentation: negativePresentation,
            #negativeRebuttal: negativeRebuttal,
            #winner: winner,
            #comments: comments,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> startArenaDebate(String? roomId) => (super.noSuchMethod(
        Invocation.method(
          #startArenaDebate,
          [roomId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>?> getChallenge(String? challengeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChallenge,
          [challengeId],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<_i6.UserProfile>> getAvailableModerators({
    int? limit = 10,
    String? excludeArenaId,
    List<String>? excludeUserIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableModerators,
          [],
          {
            #limit: limit,
            #excludeArenaId: excludeArenaId,
            #excludeUserIds: excludeUserIds,
          },
        ),
        returnValue:
            _i5.Future<List<_i6.UserProfile>>.value(<_i6.UserProfile>[]),
      ) as _i5.Future<List<_i6.UserProfile>>);

  @override
  _i5.Future<List<_i6.UserProfile>> getAvailableJudges({
    int? limit = 10,
    String? excludeArenaId,
    List<String>? excludeUserIds,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableJudges,
          [],
          {
            #limit: limit,
            #excludeArenaId: excludeArenaId,
            #excludeUserIds: excludeUserIds,
          },
        ),
        returnValue:
            _i5.Future<List<_i6.UserProfile>>.value(<_i6.UserProfile>[]),
      ) as _i5.Future<List<_i6.UserProfile>>);

  @override
  _i5.Future<void> sendArenaRoleNotification({
    required String? userId,
    required String? arenaId,
    required String? topic,
    required String? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendArenaRoleNotification,
          [],
          {
            #userId: userId,
            #arenaId: arenaId,
            #topic: topic,
            #role: role,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getActiveArenaRooms() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveArenaRooms,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> updateArenaRoomJudgeCount(
    String? roomId,
    int? judgeCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArenaRoomJudgeCount,
          [
            roomId,
            judgeCount,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateArenaRoomStatus(
    String? roomId,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArenaRoomStatus,
          [
            roomId,
            newStatus,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateArenaJudgingEnabled(
    String? roomId,
    bool? judgingEnabled,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArenaJudgingEnabled,
          [
            roomId,
            judgingEnabled,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> respondToArenaRoleNotification({
    required String? notificationId,
    required String? response,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #respondToArenaRoleNotification,
          [],
          {
            #notificationId: notificationId,
            #response: response,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.UserProfile>> getAllUsers({int? limit = 100}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i6.UserProfile>>.value(<_i6.UserProfile>[]),
      ) as _i5.Future<List<_i6.UserProfile>>);

  @override
  _i5.Future<List<_i6.UserProfile>> searchUsers(
    String? query, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i6.UserProfile>>.value(<_i6.UserProfile>[]),
      ) as _i5.Future<List<_i6.UserProfile>>);

  @override
  _i5.Future<void> debugUserSearch() => (super.noSuchMethod(
        Invocation.method(
          #debugUserSearch,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> testRealtimeConnection() => (super.noSuchMethod(
        Invocation.method(
          #testRealtimeConnection,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cleanupAbandonedArenaRooms() => (super.noSuchMethod(
        Invocation.method(
          #cleanupAbandonedArenaRooms,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> forceCleanupAllOldArenaRooms() => (super.noSuchMethod(
        Invocation.method(
          #forceCleanupAllOldArenaRooms,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAllArenaRooms() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllArenaRooms,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> forceCloseArenaRoom(String? roomId) => (super.noSuchMethod(
        Invocation.method(
          #forceCloseArenaRoom,
          [roomId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> createManualArenaRoom({
    required String? creatorId,
    required String? topic,
    String? description,
    int? maxParticipants = 1000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createManualArenaRoom,
          [],
          {
            #creatorId: creatorId,
            #topic: topic,
            #description: description,
            #maxParticipants: maxParticipants,
          },
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createManualArenaRoom,
            [],
            {
              #creatorId: creatorId,
              #topic: topic,
              #description: description,
              #maxParticipants: maxParticipants,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createScheduledArenaRoom({
    required String? creatorId,
    required String? topic,
    String? description,
    required DateTime? scheduledTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createScheduledArenaRoom,
          [],
          {
            #creatorId: creatorId,
            #topic: topic,
            #description: description,
            #scheduledTime: scheduledTime,
          },
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createScheduledArenaRoom,
            [],
            {
              #creatorId: creatorId,
              #topic: topic,
              #description: description,
              #scheduledTime: scheduledTime,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> createSimpleArenaRoom({
    required String? creatorId,
    required String? topic,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSimpleArenaRoom,
          [],
          {
            #creatorId: creatorId,
            #topic: topic,
            #description: description,
          },
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createSimpleArenaRoom,
            [],
            {
              #creatorId: creatorId,
              #topic: topic,
              #description: description,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getJoinableArenaRooms() =>
      (super.noSuchMethod(
        Invocation.method(
          #getJoinableArenaRooms,
          [],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> joinArenaRoom({
    required String? roomId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinArenaRoom,
          [],
          {
            #roomId: roomId,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cleanupUnusedDiscussionRooms() => (super.noSuchMethod(
        Invocation.method(
          #cleanupUnusedDiscussionRooms,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> forceCleanupAllOldDiscussionRooms() => (super.noSuchMethod(
        Invocation.method(
          #forceCleanupAllOldDiscussionRooms,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> oneTimeCleanupOldDiscussionRooms() => (super.noSuchMethod(
        Invocation.method(
          #oneTimeCleanupOldDiscussionRooms,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> sendGift({
    required String? giftId,
    required String? senderId,
    required String? recipientId,
    required String? roomId,
    required int? cost,
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendGift,
          [],
          {
            #giftId: giftId,
            #senderId: senderId,
            #recipientId: recipientId,
            #roomId: roomId,
            #cost: cost,
            #message: message,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i9.GiftTransaction>> getRoomGiftTransactions(
    String? roomId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoomGiftTransactions,
          [roomId],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i9.GiftTransaction>>.value(
            <_i9.GiftTransaction>[]),
      ) as _i5.Future<List<_i9.GiftTransaction>>);

  @override
  _i5.Future<List<_i9.GiftTransaction>> getUserGiftsSent(
    String? userId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGiftsSent,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i9.GiftTransaction>>.value(
            <_i9.GiftTransaction>[]),
      ) as _i5.Future<List<_i9.GiftTransaction>>);

  @override
  _i5.Future<List<_i9.GiftTransaction>> getUserGiftsReceived(
    String? userId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGiftsReceived,
          [userId],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i9.GiftTransaction>>.value(
            <_i9.GiftTransaction>[]),
      ) as _i5.Future<List<_i9.GiftTransaction>>);

  @override
  _i5.Future<bool> addCoinsToUser(
    String? userId,
    int? amount, {
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCoinsToUser,
          [
            userId,
            amount,
          ],
          {#reason: reason},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<String?> createPingRequest({
    required String? fromUserId,
    required String? fromUsername,
    required String? toUserId,
    required String? toUsername,
    required String? roleType,
    required String? debateTitle,
    required String? debateDescription,
    required String? category,
    required String? arenaRoomId,
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPingRequest,
          [],
          {
            #fromUserId: fromUserId,
            #fromUsername: fromUsername,
            #toUserId: toUserId,
            #toUsername: toUsername,
            #roleType: roleType,
            #debateTitle: debateTitle,
            #debateDescription: debateDescription,
            #category: category,
            #arenaRoomId: arenaRoomId,
            #message: message,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getPendingPingRequests(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingPingRequests,
          [userId],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<bool> updatePingRequestStatus({
    required String? pingId,
    required String? status,
    String? response,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePingRequestStatus,
          [],
          {
            #pingId: pingId,
            #status: status,
            #response: response,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i2.RealtimeSubscription subscribeToPingRequests(
    String? userId,
    dynamic Function(_i2.RealtimeMessage)? callback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToPingRequests,
          [
            userId,
            callback,
          ],
        ),
        returnValue: _FakeRealtimeSubscription_8(
          this,
          Invocation.method(
            #subscribeToPingRequests,
            [
              userId,
              callback,
            ],
          ),
        ),
      ) as _i2.RealtimeSubscription);

  @override
  _i5.Future<void> cleanupExpiredPingRequests() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredPingRequests,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [LiveKitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveKitService extends _i1.Mock implements _i10.LiveKitService {
  MockLiveKitService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onParticipantConnected(
          dynamic Function(_i11.RemoteParticipant)? _onParticipantConnected) =>
      super.noSuchMethod(
        Invocation.setter(
          #onParticipantConnected,
          _onParticipantConnected,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onParticipantDisconnected(
          dynamic Function(_i11.RemoteParticipant)?
              _onParticipantDisconnected) =>
      super.noSuchMethod(
        Invocation.setter(
          #onParticipantDisconnected,
          _onParticipantDisconnected,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onTrackSubscribed(
          dynamic Function(
            _i11.RemoteTrackPublication<_i11.RemoteTrack>,
            _i11.RemoteParticipant,
          )? _onTrackSubscribed) =>
      super.noSuchMethod(
        Invocation.setter(
          #onTrackSubscribed,
          _onTrackSubscribed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onTrackUnsubscribed(
          dynamic Function(
            _i11.RemoteTrackPublication<_i11.RemoteTrack>,
            _i11.RemoteParticipant,
          )? _onTrackUnsubscribed) =>
      super.noSuchMethod(
        Invocation.setter(
          #onTrackUnsubscribed,
          _onTrackUnsubscribed,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onError(dynamic Function(String)? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onConnected(dynamic Function()? _onConnected) => super.noSuchMethod(
        Invocation.setter(
          #onConnected,
          _onConnected,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onDisconnected(dynamic Function()? _onDisconnected) => super.noSuchMethod(
        Invocation.setter(
          #onDisconnected,
          _onDisconnected,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onMetadataChanged(
          dynamic Function(
            String,
            Map<String, dynamic>,
          )? _onMetadataChanged) =>
      super.noSuchMethod(
        Invocation.setter(
          #onMetadataChanged,
          _onMetadataChanged,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onSpeakingChanged(
          dynamic Function(
            String,
            bool,
          )? _onSpeakingChanged) =>
      super.noSuchMethod(
        Invocation.setter(
          #onSpeakingChanged,
          _onSpeakingChanged,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onAudioLevelChanged(
          dynamic Function(
            String,
            double,
          )? _onAudioLevelChanged) =>
      super.noSuchMethod(
        Invocation.setter(
          #onAudioLevelChanged,
          _onAudioLevelChanged,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get isMuted => (super.noSuchMethod(
        Invocation.getter(#isMuted),
        returnValue: false,
      ) as bool);

  @override
  List<_i11.RemoteParticipant> get remoteParticipants => (super.noSuchMethod(
        Invocation.getter(#remoteParticipants),
        returnValue: <_i11.RemoteParticipant>[],
      ) as List<_i11.RemoteParticipant>);

  @override
  int get connectedPeersCount => (super.noSuchMethod(
        Invocation.getter(#connectedPeersCount),
        returnValue: 0,
      ) as int);

  @override
  Map<String, bool> get allSpeakingStates => (super.noSuchMethod(
        Invocation.getter(#allSpeakingStates),
        returnValue: <String, bool>{},
      ) as Map<String, bool>);

  @override
  List<String> get currentSpeakers => (super.noSuchMethod(
        Invocation.getter(#currentSpeakers),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool isUserSpeaking(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #isUserSpeaking,
          [userId],
        ),
        returnValue: false,
      ) as bool);

  @override
  double getUserAudioLevel(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserAudioLevel,
          [userId],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i5.Future<void> adaptToNetworkConditions() => (super.noSuchMethod(
        Invocation.method(
          #adaptToNetworkConditions,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> connect({
    required String? serverUrl,
    required String? roomName,
    required String? token,
    required String? userId,
    required String? userRole,
    required String? roomType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {
            #serverUrl: serverUrl,
            #roomName: roomName,
            #token: token,
            #userId: userId,
            #userRole: userRole,
            #roomType: roomType,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> enableAudio() => (super.noSuchMethod(
        Invocation.method(
          #enableAudio,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disableAudio() => (super.noSuchMethod(
        Invocation.method(
          #disableAudio,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> toggleMute() => (super.noSuchMethod(
        Invocation.method(
          #toggleMute,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, bool> getNoiseCancellationStatus() => (super.noSuchMethod(
        Invocation.method(
          #getNoiseCancellationStatus,
          [],
        ),
        returnValue: <String, bool>{},
      ) as Map<String, bool>);

  @override
  _i5.Future<void> testNoiseCancellation() => (super.noSuchMethod(
        Invocation.method(
          #testNoiseCancellation,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> muteParticipant(String? participantIdentity) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteParticipant,
          [participantIdentity],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unmuteParticipant(String? participantIdentity) =>
      (super.noSuchMethod(
        Invocation.method(
          #unmuteParticipant,
          [participantIdentity],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> muteAllParticipants() => (super.noSuchMethod(
        Invocation.method(
          #muteAllParticipants,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool isParticipantMuted(_i11.RemoteParticipant? participant) =>
      (super.noSuchMethod(
        Invocation.method(
          #isParticipantMuted,
          [participant],
        ),
        returnValue: false,
      ) as bool);

  @override
  void forceUpdateRole(
    String? newRole,
    String? roomType,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #forceUpdateRole,
          [
            newRole,
            roomType,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> forceSetupJudgeAudio() => (super.noSuchMethod(
        Invocation.method(
          #forceSetupJudgeAudio,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void updateMetadata(Map<String, dynamic>? metadata) => super.noSuchMethod(
        Invocation.method(
          #updateMetadata,
          [metadata],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> unpublishAllTracks() => (super.noSuchMethod(
        Invocation.method(
          #unpublishAllTracks,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> testServerConnectivity(String? serverUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #testServerConnectivity,
          [serverUrl],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void simulateSpeaking(
    String? userId,
    bool? isSpeaking,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #simulateSpeaking,
          [
            userId,
            isSpeaking,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic> getTrackStats() => (super.noSuchMethod(
        Invocation.method(
          #getTrackStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> getGlobalTrackStats() => (super.noSuchMethod(
        Invocation.method(
          #getGlobalTrackStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  List<String> detectTrackLeaks() => (super.noSuchMethod(
        Invocation.method(
          #detectTrackLeaks,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<void> cleanupLeakedTracks() => (super.noSuchMethod(
        Invocation.method(
          #cleanupLeakedTracks,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
